/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BattlePact: typeof import('./src/components/BattlePact.vue')['default']
    BattleResult: typeof import('./src/components/BattleResult.vue')['default']
    BattleScreen: typeof import('./src/components/BattleScreen.vue')['default']
    BattleStarter: typeof import('./src/components/BattleStarter.vue')['default']
    CreateCard: typeof import('./src/components/CreateCard.vue')['default']
    CreateItem: typeof import('./src/components/CreateItem.vue')['default']
    CreateName: typeof import('./src/components/CreateName.vue')['default']
    CreatePact: typeof import('./src/components/CreatePact.vue')['default']
    CreateStats: typeof import('./src/components/CreateStats.vue')['default']
    DayCard: typeof import('./src/components/DayCard.vue')['default']
    DayHeader: typeof import('./src/components/DayHeader.vue')['default']
    DayIndex: typeof import('./src/components/DayIndex.vue')['default']
    DayList: typeof import('./src/components/DayList.vue')['default']
    DayNext: typeof import('./src/components/DayNext.vue')['default']
    LayoutBlock: typeof import('./src/components/layouts/LayoutBlock.vue')['default']
    LayoutSidebar: typeof import('./src/components/layouts/LayoutSidebar.vue')['default']
    ModeButtons: typeof import('./src/components/ModeButtons.vue')['default']
    WinnerCard: typeof import('./src/components/WinnerCard.vue')['default']
    WinnerList: typeof import('./src/components/WinnerList.vue')['default']
  }
}
